[workspace]
# List of crates included in this workspace
members = ["arbiter-core", "arbiter-derive"]

# List of crates excluded from this workspace
exclude = ["benches"]

# Package configuration
[package]
name = "arbiter"
version = "0.3.2"
edition = "2021"
authors = ["Waylon Jepsen <waylonjepsen1@gmail.com>", "Colin Roberts <colin@autoparallel.xyz>"]
description = "Allowing smart contract developers to do simulation driven development via an EVM emulator"
license = "Apache-2.0"
keywords = ["ethereum", "evm", "emulator", "testing", "smart-contracts"]

# Binary configuration
[[bin]]
name = "arbiter"
path = "bin/main.rs"


# Dependencies for the release build
[dependencies]
# Command line and config
clap = { version = "=4.3.0", features = ["derive"] }
serde = { version = "=1.0.163", features = ["derive"] }
toml = { version = "=0.8.1" }

# Building files
quote = { version = "=1.0.33" }

# Errors
thiserror = { version = "=1.0.47" }

# Dependencies for the test build and development
[dev-dependencies]
assert_cmd = { version = "=2.0.12" }

# Release profile
[profile.release]
# Link-Time Optimization can improve runtime at cost of build time
lto = true
# The Rust compiler splits your crate into multiple codegen units to parallelize (and thus speed up) compilation but at the cost of optimization. 
# This setting tells the compiler to use only one codegen unit, which will slow down compilation but improve optimization.
codegen-units = 1
