[workspace]
# List of crates included in this workspace
members = ["arbiter-core"]

# List of crates excluded from this workspace
exclude = ["benches"]

# Package configuration
[package]
name = "arbiter"
version = "0.3.2"
edition = "2021"
authors = ["Colin Roberts", "Waylon Jepsen"]

# Binary configuration
[[bin]]
name = "arbiter"
path = "bin/main.rs"


# Dependencies for the release build
[dependencies]
# Command line and config
clap = { version = "4.3.0", features = ["derive"] }
serde = { version = "1.0.163", features = ["derive"] }
toml = "0.8.0"

# Building files
quote = "1.0.28"

# Errors
thiserror = "1.0.40"

# Dependencies for the test build and development
[dev-dependencies]
assert_cmd = "2.0.11"

# Release profile
[profile.release]
# Link-Time Optimization can improve runtime at cost of build time
lto = true
# The Rust compiler splits your crate into multiple codegen units to parallelize (and thus speed up) compilation but at the cost of optimization. 
# This setting tells the compiler to use only one codegen unit, which will slow down compilation but improve optimization.
codegen-units = 1
