[workspace]
# List of crates included in this workspace
members = ["arbiter-core", "arbiter-derive"]

# List of crates excluded from this workspace
exclude = ["benches"]

# Package configuration
[package]
name = "arbiter"
version = "0.4.8"
edition = "2021"
authors = ["Waylon Jepsen <waylonjepsen1@gmail.com>", "Colin Roberts <colin@autoparallel.xyz>"]
description = "Allowing smart contract developers to do simulation driven development via an EVM emulator"
license = "Apache-2.0"
keywords = ["ethereum", "evm", "emulator", "testing", "smart-contracts"]

# Binary configuration
[[bin]]
name = "arbiter"
path = "bin/main.rs"

[workspace.dependencies]
ethers = { version = "=2.0.10" }
serde = { version = "=1.0.192", features = ["derive"] }
serde_json = { version = "=1.0.108" }
revm = { version = "=3.5.0", features = [ "ethersdb", "std", "serde"] }
revm-primitives = { version = "1.3.0" }
thiserror = { version = "=1.0.50" }
syn = { version = "=2.0.39" }
quote = { version = "=1.0.33" }
proc-macro2 = { version = "=1.0.69" }
tokio = { version = "1.34.0", features = ["macros", "full"] }

# Dependencies for the release build
[dependencies]
arbiter-core = { version = "0.7.4", path = "arbiter-core" }

# Command line and config
clap = { version = "=4.4.7", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
config = { version = "=0.13.3" }
ethers.workspace = true
revm.workspace = true
toml = { version = "=0.8.8" }
proc-macro2.workspace = true
syn.workspace = true
Inflector = { version = "=0.11.4" }

# Building files
quote.workspace = true
foundry-config = { version = "=0.2.0" }

# Errors
thiserror.workspace = true

# Dependencies for the test build and development
[dev-dependencies]
tokio.workspace = true
tempfile = { version = "=3.8.1" }
assert_cmd = { version = "=2.0.12" }
rayon = { version = "1.8.0" }
revm-primitives.workspace = true

# Release profile
[profile.release]
# Link-Time Optimization can improve runtime at cost of build time
lto = true
# The Rust compiler splits your crate into multiple codegen units to parallelize (and thus speed up) compilation but at the cost of optimization. 
# This setting tells the compiler to use only one codegen unit, which will slow down compilation but improve optimization.
codegen-units = 1


