[profile.default] # all profiles inherit from this
src = 'lib/'
out = 'out/' # default
test = 'test' # default
libs = ['lib']
cache = false # !important! breaks echidna if cache = true.
remappings = [
    '@forge-std/=lib/forge-std/src/',
    '@solmate/=lib/solmate/src/',
    '@solstat/=lib/solstat/src/',
]
ethers-rs  = "=2.0.0"