[Bob]
type = "TimedMessage"
delay = 20
receive_data = "Hey"
send_data = "Hey there"
count = 0
max_count = 3

[Alice]
type = "TimedMessage"
delay = 10
receive_data = "Hey"
send_data = "..."
count = 0
max_count = 3
