[[ping]]
TimedMessage = { delay = 1, receive_data = "pong", send_data = "ping", count = 0, max_count = 3, startup_message = "ping" }

[[ping]]
TimedMessage = { delay = 1, receive_data = "zim", send_data = "zam", count = 0, max_count = 3, startup_message = "zam" }

[[pong]]
TimedMessage = { delay = 1, receive_data = "ping", send_data = "pong", count = 0, max_count = 3 }

[[pong]]
TimedMessage = { delay = 1, receive_data = "zam", send_data = "zim", count = 0, max_count = 3 }
