[package]
name = "arbiter-core"
version = "0.6.1"
edition = "2021"
authors = ["Waylon Jepsen <waylonjepsen1@gmail.com>", "Colin Roberts <colin@autoparallel.xyz>"]
description = "Allowing smart contract developers to do simulation driven development via an EVM emulator"
license = "Apache-2.0"
keywords = ["ethereum", "evm", "emulator", "testing", "smart-contracts"]
readme = "../README.md"

[features]
contracts = []

# Dependencies for the release build
[dependencies]

# Ethereum and EVM
ethers = { version = "=2.0.10"}
revm = { version = "=3.5.0", features = ["serde", "std"] }
revm-primitives = "=1.3.0"

# Serialization
bytes = { version = "=1.5.0" }
serde = { version = "=1.0.188", features = ["derive"] }
serde_json = { version = "=1.0.107" }

# Concurrency/async
tokio = { version = "=1.32.0", features = ["macros", "full"] }
async-trait =  { version = "=0.1.73" }
crossbeam-channel =  { version = "=0.5.8" }
atomic_enum = { version = "=0.2.0" }
futures-timer = { version = "=3.0.2" }
futures-locks = { version = "=0.7.1" }

# Randomness
rand =  { version = "=0.8.5" }
rand_distr = { version = "=0.4.3" }
statrs = { version = "=0.16.0" }
RustQuant = { version = "=0.0.33", features = ["seedable"]}

# Errors
thiserror =  { version = "=1.0.49" }

# Logging
futures-util =  { version = "=0.3.28" }
tracing = "0.1.37"

# Dependencies for the test build and development
[dev-dependencies]
arbiter-derive = { path = "../arbiter-derive" }
hex = { version = "=0.4.3", default-features = false }
anyhow =  { version = "=1.0.75" }
test-log =  { version = "=0.2.13" }
tracing-test = "0.2.4"

futures =  { version = "=0.3.28" }
assert_matches =  { version = "=1.5" }

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
