[sim]
timestep = 0.0027397
timescale = "years"
num_steps = 365
initial_price = 1
drift = 0.1
volatility = 0.07
seed = 887
ou_mean_reversion_speed = 50
ou_mean = 1

[chain]
contract = "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
rpc_url = "https://eth-mainnet.g.alchemy.com/v2/I93POQk49QE9O-NuOz7nj7sbiluW76it"