rpc_url = "https://eth-mainnet.g.alchemy.com/v2/I93POQk49QE9O-NuOz7nj7sbiluW76it"

[sim]
timestep = 0.0027397
timescale = "years"
num_steps = 365
initial_price = 1196.54
drift = 0.1
volatility = 0.7
seed = 887

[chain]
contract_address = "0x8ad599c3a0ff1de082011efddc58f1908eb6e6d8"
